spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yue_blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: root
    # sa-token配置
  sa-token:
    # token名称 (同时也是cookie名称)
    token-name: Authentication
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 2592000
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: -1
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    allow-concurrent-login: true
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: false
    # token风格
    token-style: uuid
    # jwt秘钥
    jwt-secret-key: yueqiaoblog
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      # 连接空闲超过N(s秒、ms毫秒，不加单位时使用毫秒)后关闭，0为禁用，这里配置值和tcp-keepalive值一致
      timeout: 60s
      # Lettuce连接池配置
      lettuce:
        pool:
          # 允许最大连接数，默认8（负值表示没有限制），推荐值：大于cpu * 2，通常为(cpu * 2) + 2
          max-active: 10
          # 最大空闲连接数，默认8，推荐值：cpu * 2
          max-idle: 8
          # 最小空闲连接数，默认0
          min-idle: 0
          # 连接用完时，新的请求等待时间(s秒、ms毫秒)，超过该时间抛出异常，默认-1（负值表示没有限制）
          max-wait: 5s