spring:
  application:
    name: yueblog
  profiles:
    active: dev
  datasource:
    # druid ?????
    druid:
      # ?????????????
      initial-size: 5
      # ??????????
      min-idle: 5
      # ?????????
      max-active: 20
      # ????????????????
      max-wait: 60000
      # ??????????????????timeBetweenEvictionRunsMillis???validationQuery?????????
      test-while-idle: true
      # ?????????????testWhileIdel?????
      time-between-eviction-runs-millis: 60000
      # ????????????????????????????????????(??????????????)
      min-evictable-idle-time-millis: 30000
      # ??????????????sql ?????????(oracle?? select 1 from dual)
      validation-query: select 'x'
      # ????????validationQuery????????,???????,???true
      test-on-borrow: false
      # ????????validationQuery????????,???????,???true
      test-on-return: false
      # ????preparedStatement, ???PSCache,PSCache???????????????????oracle,?mysql??????
      pool-prepared-statements: false
      # ????????filters????????sql?????stat: ?????Slf4j:?????waLL: ??sqL??
      filters: stat,wall,slf4j
      # ???PSCache???????0????0??poolPreparedStatements???????true??Druid??????Oracle?PSCache??????????????????????????100
      max-pool-prepared-statement-per-connection-size: -1
      # ????DruidDataSource?????
      use-global-data-source-stat: true
      # ??connectProperties?????mergeSql????SQL??
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

      web-stat-filter:
        # ????StatFilter???true
        enabled: true
        # ??????
        url-pattern: /*
        # ???????
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico

      stat-view-servlet:
        # ????StatViewServlet???true
        enabled: true
        # ?????/druid?????StatViewServlet
        url-pattern: /druid/*
        # ????????
        reset-enable: false
        # ?????????????????root
        login-username: druid
        login-password: druid
        # IP???
        allow: 127.0.0.1
        # IP??????????deny???allow?
        deny: