package top.yueqiao.yueblog;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

/**
 * @author yueqiao
 */
@SpringBootApplication
public class YueBlogApplication {

    public static void main(String[] args) {
        SpringApplication.run(YueBlogApplication.class, args);
    }

}
